image: alpine:latest

pages:
  script:
    - mkdir .public
    - cp index.html .public/
    - cp style.css .public/ || true
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main
